# Generated by Django 4.1.1 on 2022-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostar',
            field=models.BooleanField(default=True),
        ),
    ]
