# Generated by Django 4.1.1 on 2022-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostar',
            new_name='mostrar',
        ),
    ]
